### Задача 1

1. Подгрузите файл **train_vector_1.csv** с помощью функции **np.loadtxt**. 

2. Назовите подгруженный массив my_array.

3. Убедитесь, что подгруженный массив имеет тип np.ndarray (выведите тип переменной my_array).

Ссылка на файл: https://drive.google.com/open?id=1ngnrhmoMInequrA6JyAe90lEPhcbi0iH

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


**Решение:**

In [ ]:
import numpy as np

my_array = np.loadtxt ('/content/drive/My Drive/train_vector_1.csv', delimiter=',', skiprows=1) 

print ("Подгруженный массив имеет тип:", type(my_array))       




### Задача 2

Напишите код, который считает среднее значение всех элементов массива (без использования встроенных функций np.mean и т. д.). Для решения задачи воспользуйтесь циклом.
* С помощью команды %%timeit отобразите время выполнения написанного кода.
* Преобразуйте массив my_array в список (с помощью метода list()), сохраните его в переменной my_list.
* В новой ячейке посчитайте среднее значение всех элементов списка (воспользуйтесь тем же кодом, что и для массива).
* Командой %%timeit отобразите время выполнения и этой ячейки.

**Решение:**

In [ ]:
%%timeit -n 5 -r 10                                  

mean_my_array = 0                                    # Переменная которая будет хранить среднее значение всех элементов массива
sum_my_array = 0                                     # Переменная которая будет хранить сумму всех элементов массива

for i in my_array:
  sum_my_array += i                                  # Ищем сумму всех элементов массива my_array
  mean_my_array = sum_my_array / my_array.size       # Находим среднее значение разделив общую сумму на кол-во элементов в массиве

print ("Среднее значение всех элементов массива равна:", mean_my_array)

my_list = list(my_array)                             #Преобразование массива в список 




Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее зн

In [ ]:
%%timeit -n 5 -r 10

sum_my_list = 0
mean_my_list = 0

for i in my_list:
  sum_my_list += i                                                     # Вычисляем сумму всех элементов в списке
  mean_my_list = sum_my_list / len(my_list)                            # Так же находим среднее значение всех элементов в списке

print ("Среднее значение всех элементов массива равна:", mean_my_list)

Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее значение всех элементов массива равна: 3.0543624161073835
Среднее зн

### Задача 3

Подгрузите файл **iris.csv** с помощью встроенной функции **np.loadtxt**. Назовите его my_2d_array. Напишите код, который считает сумму элементов массива по столбцам (для решения данной задачи воспользуйтесь разделом ноутбук "Операции с двумерными массивами и встроенные методы").

**Решение:**

In [ ]:
my_2d_array = np.loadtxt('/content/drive/My Drive/iris.csv', delimiter=',', skiprows=1)
print (my_2d_array.sum(axis=0))


[11175.    876.5   458.6   563.7   179.9]


### Задача 4 

* Используя библиотеку numpy, создайте массив 3x3, значения которого находятся в диапазоне от 11 до 40 (раздел "Семплирование из распределений"). 

* Не используя цикл for,  выведите на экран список элементов, которые меньше 20 (раздел "Индексация").

* Просуммируйте все элементы, не используя цикл for (раздел "Встроенные методы").


**Решение:**

In [ ]:
my_3x3_array = np.random.randint (11,40, (3,3))                                             # Создаем двумерный массив (матрицу) 3х3 с произволными значениями в диапазоне от 11 до 40
print (my_3x3_array)                                                                        # Просто вывести массив для наглядности

print ("Элементы значения которых меньше 20:", my_3x3_array[my_3x3_array < 20])           # Вывести все элементы списком значения которых меньше 20

sum_my_3x3_array = my_3x3_array.sum()                                                        # Находим сумму всех элементов данного массива
print ("Сумма всех элементов массива равна:", sum_my_3x3_array)

#Или можно сразу так
print ("Сумма всех элементов массива равна:", my_3x3_array.sum())

[[14 12 32]
 [11 30 17]
 [34 22 26]]
Элементы значения которых меньше 20: [14 12 11 17]
Сумма всех элементов массива равна: 198
Сумма всех элементов массива равна: 198


### Задача 5

* Создайте массив, который будет содержать списки с именем студента(str), его возрастом(int) и средней оценкой(float) (обратите внимание на пример с занятия со списком автомобильных регионов).
* Отсортируйте такой массив (обратите внимание на параметр order метода sort()).
* Замените значение, отвечающее за возраст, у всех студентов на одно и то же, например, 10. Отсортируйте такой массив. 

**Решение:**

In [ ]:
my_type = [('name', '<U32'), ('age', np.int32), ('rating', np.float64)]

students_list = [('Феодул', 22, 4.85), ('Агафангел', 24, 4.37), ('Гермоген', 21, 3.97), ('Епимах', 27, 4.18), ('Каллистрат', 18, 3.55), ('Павсикакий', 23, 4.05), ('Ферапонт', 30, 4.99)]

students_array = np.array (students_list, dtype = my_type)     #Создаем numpy-массив из указанных значений и задаем тип данных для каждого столбца

students_array.sort(order = 'age')
print (students_array,'\n')                                          #Печать отсортированного массива по возрасту

#for i in students_array:                                     #Заменим возраст всех студентов на значение 10
#  i[1] = 10

students_array['age'] = 25

print ("Сортированный список после изменения значения возраста на 10\n")

students_array.sort(order = 'age')                            #Снова отсортируем массив по возрасту
print (students_array)                                        #Печать вновь отсортированного массива

[('Каллистрат', 18, 3.55) ('Гермоген', 21, 3.97) ('Феодул', 22, 4.85)
 ('Павсикакий', 23, 4.05) ('Агафангел', 24, 4.37) ('Епимах', 27, 4.18)
 ('Ферапонт', 30, 4.99)] 

Сортированный список после изменения значения возраста на 10

[('Агафангел', 25, 4.37) ('Гермоген', 25, 3.97) ('Епимах', 25, 4.18)
 ('Каллистрат', 25, 3.55) ('Павсикакий', 25, 4.05) ('Феодул', 25, 4.85)
 ('Ферапонт', 25, 4.99)]
