### Задача 1

* Подгрузите массив **iris.csv** и назовите его my_array. 

* Создайте двумерный массив из случайных чисел той же размерности, что и my_array (раздел "Семплирование из распределений", потребуется использовать размерность массива my_array).

* Назовите его my_generated_array.

**Решение:**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
import numpy as np


my_array = np.loadtxt ('/content/iris.csv', delimiter=',', skiprows=1) 


my_generated_array = np.random.randint(0, 100, (my_array.shape))    #Создание массива той же размерности что и массив my_array со случайными значениями чисел


print ("Размер массива my_array:", my_array.shape)
print ("Размер массива my_generated_array:", my_generated_array.shape)


Размер массива my_array: (150, 5)
Размер массива my_generated_array: (150, 5)


### Задача 2

* Выполните поэлементное умножение my_array на my_generated_array (раздел "Векторные операции").

* Склейте массивы my_array, my_generated_array в один (могут помочь методы np.concatenate, np.vstack, np.hstack).

* Возьмите склеенный массив и разделите его на равные части (больше двух). Можно сделать вручную через циклы либо воспользоваться методом vsplit.

**Решение:**

In [ ]:
import numpy as np

multiplication = my_array * my_generated_array      #Поэлементное умножение двух массивов и запись результата в переменную multiplication 
print (multiplication.shape)     #Размер массива после операции поэлементного умножения

c1 = np.vstack((my_array, my_generated_array))    #Объединение двух массивов
c2 = np.concatenate ((my_array, my_generated_array))
print ("Размерность с2 - concatenate:", c2.shape)

c3 = np.hstack((my_array, my_generated_array))
print ("Размерность c3 - hstack", c3.shape)


print ("Размерность c1 - vstack", c1.shape)        #Размер объединенных массивов

cut_array = np.vsplit (c1, 5)      #Разделение массива на 5 равных частей
print ("Длина разрезанного массива", len (cut_array))                     #Длина разрезанного массива
print (cut_array[1].shape)
print (cut_array)



(150, 5)
Размерность с2 - concatenate: (300, 5)
Размерность c3 - hstack (150, 10)
Размерность c1 - vstack (300, 5)
Длина разрезанного массива 5
(60, 5)
[array([[ 0. ,  5.1,  3.5,  1.4,  0.2],
       [ 1. ,  4.9,  3. ,  1.4,  0.2],
       [ 2. ,  4.7,  3.2,  1.3,  0.2],
       [ 3. ,  4.6,  3.1,  1.5,  0.2],
       [ 4. ,  5. ,  3.6,  1.4,  0.2],
       [ 5. ,  5.4,  3.9,  1.7,  0.4],
       [ 6. ,  4.6,  3.4,  1.4,  0.3],
       [ 7. ,  5. ,  3.4,  1.5,  0.2],
       [ 8. ,  4.4,  2.9,  1.4,  0.2],
       [ 9. ,  4.9,  3.1,  1.5,  0.1],
       [10. ,  5.4,  3.7,  1.5,  0.2],
       [11. ,  4.8,  3.4,  1.6,  0.2],
       [12. ,  4.8,  3. ,  1.4,  0.1],
       [13. ,  4.3,  3. ,  1.1,  0.1],
       [14. ,  5.8,  4. ,  1.2,  0.2],
       [15. ,  5.7,  4.4,  1.5,  0.4],
       [16. ,  5.4,  3.9,  1.3,  0.4],
       [17. ,  5.1,  3.5,  1.4,  0.3],
       [18. ,  5.7,  3.8,  1.7,  0.3],
       [19. ,  5.1,  3.8,  1.5,  0.3],
       [20. ,  5.4,  3.4,  1.7,  0.2],
       [21. ,  5.1,  3.7,  1

### Задача 3

* Найдите все элементы массива my_array, которые больше трех и меньше 5 одновременно. Используйте методологию подвыборки массива с условием (раздел "Индексация").

**Решение:**

In [ ]:
selection = (my_array[(my_array > 3) & (my_array < 5)])                        #Присвоить переменной значения, которые удовлетворяют заданному условию
print ("Элементы массива my_array, которые больше 3 и меньше 5:\n", selection)

print ("\nДругим способом:")
print (my_array[(my_array > 3) & (my_array < 5)])

Элементы массива my_array, которые больше 3 и меньше 5:
 [3.5 4.9 4.7 3.2 4.6 3.1 4.  3.6 3.9 4.6 3.4 3.4 4.4 4.9 3.1 3.7 4.8 3.4
 4.8 4.3 4.  4.4 3.9 3.5 3.8 3.8 3.4 3.7 4.6 3.6 3.3 4.8 3.4 3.4 3.5 3.4
 4.7 3.2 4.8 3.1 3.4 4.1 4.2 4.9 3.1 3.2 3.5 4.9 3.6 4.4 3.4 3.5 4.5 4.4
 3.2 3.5 3.8 4.8 3.8 4.6 3.2 3.7 3.3 3.2 4.7 3.2 4.5 3.1 4.9 4.  4.6 4.5
 3.3 4.7 4.9 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 3.1 4.4 4.5 4.1 4.5 3.9 3.2
 4.8 4.  4.9 4.7 4.3 4.4 4.8 4.5 3.5 3.8 3.7 3.9 4.5 3.4 4.5 3.1 4.7 4.4
 4.1 4.  4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3 4.1 3.3 4.9 4.5 3.6 3.2 3.2 3.8
 3.2 4.9 4.9 3.3 3.2 4.8 4.9 3.8 3.4 3.1 4.8 3.1 3.1 3.1 3.2 3.3 3.4]

Другим способом:
[3.5 4.9 4.7 3.2 4.6 3.1 4.  3.6 3.9 4.6 3.4 3.4 4.4 4.9 3.1 3.7 4.8 3.4
 4.8 4.3 4.  4.4 3.9 3.5 3.8 3.8 3.4 3.7 4.6 3.6 3.3 4.8 3.4 3.4 3.5 3.4
 4.7 3.2 4.8 3.1 3.4 4.1 4.2 4.9 3.1 3.2 3.5 4.9 3.6 4.4 3.4 3.5 4.5 4.4
 3.2 3.5 3.8 4.8 3.8 4.6 3.2 3.7 3.3 3.2 4.7 3.2 4.5 3.1 4.9 4.  4.6 4.5
 3.3 4.7 4.9 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 3.1 4.4

### Задача 4

Создайте трехмерный массив размера 2 на 3 на 4, состоящий из случайных ВЕЩЕСТВЕННЫХ чисел от 15 до 37. Используйте встроенные методы библиотеки  np.random.

**Решение:**

In [ ]:
three_array = np.random.uniform(15, 37, (2,3,4))    #Создаем трехмерный массив(тензор) из случайных вещественных чисел в диапазоне от 15 до 37 (Если поставить до 38, то могут появиться числа больше 37, так как тип float и могут быть 37.5426283, а это больше чем 37)
print (three_array)                                 #Выводим на экран в качестве проверки созданный массив
print (three_array.shape)                           #Проверка размерности созданного массива

[[[15.14912836 16.40294754 33.28664448 35.9516534 ]
  [30.80685703 15.77948815 33.82501477 29.9760616 ]
  [27.53621739 30.51088572 21.62150438 26.53781734]]

 [[22.83875777 29.00685661 34.40364865 36.43155649]
  [21.78844374 32.11726847 21.4615413  23.92886078]
  [18.98153861 27.10340483 21.86445975 19.69884137]]]
(2, 3, 4)


### Задача 5

Используя массив из предыдущей задачи, преобразуйте его в новый массив со следующими значениями:

    * "small", если значения меньше 20
    * "medium", если значения в промежутке [20, 30]
    * "large", если значения больше 30

**Решение:**

In [ ]:
signification = three_array.astype(str)                            #Преобразование в строковый тип


signification[three_array < 20] = 'small'                          #Если значение меньше 20, то присвоить 'small'
signification[three_array > 30] = 'large'                          #Если значение больше 30, то присвоить 'large'
signification[(three_array >20) & (three_array <30)] = 'mediun'    #Если значение больше 20 и меньше 30 то присвоить 'medium'

new_string_array =np.array(signification)                          #Создание нового массива с учетом новых значений

print (three_array)
print ("")
print (new_string_array)                                           #Печать нового массива

[[[15.14912836 16.40294754 33.28664448 35.9516534 ]
  [30.80685703 15.77948815 33.82501477 29.9760616 ]
  [27.53621739 30.51088572 21.62150438 26.53781734]]

 [[22.83875777 29.00685661 34.40364865 36.43155649]
  [21.78844374 32.11726847 21.4615413  23.92886078]
  [18.98153861 27.10340483 21.86445975 19.69884137]]]

[[['small' 'small' 'large' 'large']
  ['large' 'small' 'large' 'mediun']
  ['mediun' 'large' 'mediun' 'mediun']]

 [['mediun' 'mediun' 'large' 'large']
  ['mediun' 'large' 'mediun' 'mediun']
  ['small' 'mediun' 'mediun' 'small']]]
