In [ ]:
num = int(input('Введите число: '))

for i in range(num):
  print((i+1) * '@')

Введите число: 5
@
@@
@@@
@@@@
@@@@@


In [ ]:
num = int(input('Введите число: '))
i = 1
while i <= num:
  print(i *'@')
  i+=1

Введите число: 5
@
@@
@@@
@@@@
@@@@@


In [ ]:
num = int(input('Введите число:'))

for i in range(num+1):
  if i % 2 == 0:
    print (i, 'is EVEN' )
  else:
    print (f'{i} is ODD')


Введите число:10
0 is EVEN
1 is ODD
2 is EVEN
3 is ODD
4 is EVEN
5 is ODD
6 is EVEN
7 is ODD
8 is EVEN
9 is ODD
10 is EVEN


In [ ]:
num = int(input('Введите число:'))
i = 0
while i <=num:
  if i % 2 != 0:
    print (i,'is ODD')
  else:
    print (f'{i} is EVEN')
  i+=1

Введите число:10
0 is EVEN
1 is ODD
2 is EVEN
3 is ODD
4 is EVEN
5 is ODD
6 is EVEN
7 is ODD
8 is EVEN
9 is ODD
10 is EVEN


In [ ]:
num = int(input('Введите число:'))
sum = 0
for i in range(num+1):
  if (i % 3 == 0 or i % 5 == 0):
    sum = sum + i
    print (i)
print('Сумма чисел = ',sum)

Введите число:10
0
3
5
6
9
10
Сумма чисел =  33


In [ ]:
limit = int(input('Введите число:'))

arg_list =sum([n for n in range(limit+1) if (n % 3 == 0 or n % 5 == 0)])
print (arg_list)


Введите число:20
98


In [ ]:
first_lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
second_lst = [11, 12, 13 , 14, 15, 16, 17, 18, 19, 20]
joined_list=[]

for n in first_lst:
  if n % 2 != 0:
    joined_list.append(n)
for m in second_lst:
  if m % 2 == 0:
    joined_list.append(m)
print (joined_list)

[1, 3, 5, 7, 9, 12, 14, 16, 18, 20]


In [ ]:
first_lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
second_lst = [11, 12, 13 , 14, 15, 16, 17, 18, 19, 20]

odds=[n for n in first_lst if n % 2 != 0]
evens = [n for n in second_lst if n % 2 == 0]

joined_list = odds + evens
print (joined_list)


[1, 3, 5, 7, 9, 12, 14, 16, 18, 20]


In [ ]:
card = {2:+1, 3:+1, 4:+1, 5:+1, 6:+1, 7:0, 8:0, 9:0, 10:-1, 'J':-1, 'Q':-1, 'K':-1, 'A':-1}

current_hand = [2, 7,  4, 9, 'J', 4]

cards_sum = 0
for i in current_hand:
  for m in list(card.keys()):
    if i == m:
      cards_sum = cards_sum + card.get(m)

cards_sum

2

In [ ]:
card = {2:1, 3:1, 4:1, 5:1, 6:1, 7:0, 8:0, 9:0, 10:-1, 'J':-1, 'Q':-1, 'K':-1, 'A':-1}

current_hand = [2, 7,  4, 9, 'J', 4]

cards_sum = sum([card[x] for x in current_hand])
print (cards_sum)

2


In [ ]:
def square(a):
  return a**2

s_lam = lambda a:a**2
a = 2
#print (f'squarer {a} = ', square(a))

s_lam(55)

3025

In [ ]:
my = [x*x for x in range(4)]
for i in my:
  print (i)

my

0
1
4
9


[0, 1, 4, 9]

In [ ]:
def square(num):
  for i in num:
    yield i**2

for i in square([1,2,3]):
  print(i)

1
4
9


In [ ]:
p = []
for i in range (0, 1001):
  p.append(i)
print (p)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [ ]:
def IsPrime(n):
  d = 2
    for i in n:
      #while n % d != 0:
          #d += 1
          print(i)
    

IsPrime([1,2,3,4])

IndentationError: ignored

In [ ]:
def my(*num):
  a = []
  for i in num:
    a.append(i)
  return a

my(p)


In [ ]:
%%timeit -n 10 -r 20
def IsPrime(*n):
    i = 2
    while i < n/2:
     if n % i == 0:
      return print (False) 
     i+=1
    return print (True)


IsPrime(p)

In [ ]:
slovo = str(input())
a = slovo[::-1]
if slovo == a:
  print("yes")
else:
  print("no")

print (slovo)
print (a)

фывапавыф
yes
фывапавыф
фывапавыф


In [ ]:

def Pal(string):

# Идёт проверка, если перевёрнутая строка равна обычной строке, то это палиндром и возвращается значение True
    if string[::-1].startswith(string):
        return True
# Иначе же возвращаем False
    else:
        return False

Pal ('а роза упала на лапу Азора')


False

In [ ]:
def pali(data):
    data = data.replace(' ','').lower()
    return 'Палиндром' if data == data[::-1] else 'Не палиндром'

pali('а роза упала на лапу Азора')

'Палиндром'

In [ ]:
mixed = ['ма', 'про', 'мак', 'мак', 'просо', 'мак', 'просо', 'просо', 'просо', 'мак']
zolushka = list(filter(lambda x: x == 'мак' or x == 'про', mixed))
 
print (zolushka)

['про', 'мак', 'мак', 'мак', 'мак']


In [ ]:
#%%timeit -n 2 -r 5

for i in range(2,10000):
    s = 0
    for j in range(1,i):
        if i%j == 0:
            s += j
    if s == i:
        print(i)

6
28
496
8128


In [ ]:
y = int(input('Укажите верхнюю границу: '))
x = int(input('Укажите нижнюю границу: '))
 
for i in range(x,y):
    s = 1
    for j in range(2, i // 2 + 1):
        if i % j == 0:
            s += j
    if s == i:
        print(i)

Укажите верхнюю границу: 100
Укажите нижнюю границу: 2
6
28


In [ ]:
import math
from itertools import takewhile

def is_prime(n):
    return not any(True for i in range(2, math.ceil(math.sqrt(n))) if n % i == 0)

def perfects ():
    i = 2
    while True:
        mersenne = 2**i - 1
        if is_prime(mersenne):
            yield 2**(i-1)*mersenne
        i += 1

if __name__ == '__main__':
    limit = 10000
    for i in takewhile(lambda n: n <= limit, perfects()):
        print (i)

6
28
496
8128


In [ ]:
print(*[num for num in range(1, int(input())) if num == sum([i for i in range(1,num) if not num % i])])


1000
6 28 496


In [ ]:
%%timeit -n 1 -r 1

for i in range(1,100):
  s = 0 
  for j in range (1,i):
    if i % j == 0:
      s = s + j 
  if s == i:
    print (i)

6
28
1 loop, best of 1: 800 µs per loop


In [ ]:
#module_name.py
print('Module!')
def summ(a,b):
  return a + b
def diff(a,b):
  return a - b

if __name__ == '__main__':
  a=5
  b=7
  print('{} + {} = {}'.format(a,b,summ(a,b)))
  print('{} - {} = {}'.format(a,b,diff(a,b)))

Module!
5 + 7 = 12
5 - 7 = -2


In [ ]:
!python module.py

Module!


In [ ]:
from module import * # Импортируем всё содержимое нашего модуля

a=10
b=24
print('Результат: {} + {} = {}'.format(a,b,summ(a,b))) # Функции summ и diff описаны в модуле
print('Результат: {} - {} = {}'.format(a,b,diff(a,b)))

Module!
Результат: 10 + 24 = 34
Результат: 10 - 24 = -14


In [ ]:
n = int(input())
 
fact = 1
while n > 1:
    fact *= n
    n -= 1
 
print(fact)

5
120


In [ ]:
n = int(input())
 
fact = 1
i = 1 
while i <= n:
    fact *= i
    i += 1
 
print(fact)

5
120


In [ ]:
n = int(input())

factorial = 1

for i in range(2, n+1):
    factorial *= i

print(factorial)

5
120


In [ ]:
def factorial(n):
    if n == 0: return 1
    return n*factorial(n-1)

n = int(input())

print(factorial(n))

5
120


In [ ]:
print((lambda n,f : 1 if n==1 else n*f(n-1,f)) (6,(lambda n,f : 1 if n==1 else n*f(n-1,f))))
 

720


In [ ]:
def hotel_cost(Количество_ночей):
  price = Количество_ночей * 140
  return price

hotel_cost(9)

1260

In [ ]:
def plane_ride_cost(Город):
  if Город == 'Крым':
    return 120
  elif Город == 'Шри-Ланка':
    return 800
  elif Город == 'Каир':
    return 400
  elif Город == 'Сочи':
    return 120

plane_ride_cost('Сочи')

120

In [ ]:
def rental_car_cost(Количество_дней):

  price = 40
  n = 1.01

  def car_day (day):
    if day == 0:
      return 0
    return price * n + car_day(day-1)* n 


  if Количество_дней < 3:
    return round(car_day(Количество_дней),2)

  elif Количество_дней >= 3 and Количество_дней < 7:
    return round((car_day(Количество_дней) - 20),2)

  else:
    return round((car_day(Количество_дней) - 50),2)



In [ ]:
rental_car_cost(0)

0

In [ ]:
def trip_cost():
  
  Количество_ночей = int(input("Количество дней отпуска: "))
  Город = input("Место отдыха (Крым, Шри-Ланка, Каир или Сочи): ")
  Количество_дней = int(input("Количество дней аренды автомобиля: "))

  if Город != 'Крым' or 'Сочи': #  or 'Каир' or 'Шри-Ланка':
    return "Такого места нет"
  
  if Количество_дней > Количество_ночей:
   return "Ошибка !!! Аренда автомобиля не может быть больше дней отдыха."

  def hotel_cost(Количество_ночей):
    price = Количество_ночей * 140
    return price



  def plane_ride_cost(Город):
    if Город == 'Крым':
     return 120
    elif Город == 'Шри-Ланка':
     return 800
    elif Город == 'Каир':
      return 400
    elif Город == 'Сочи':
      return 120
  


  def rental_car_cost(Количество_дней):

    price = 40
    n = 1.01

    def car_day (day):
      if day == 0:
        return 0
      return price * n + car_day(day-1)* n 


    if Количество_дней < 3:
      return round(car_day(Количество_дней),2)

    elif Количество_дней >= 3 and Количество_дней < 7:
      return round((car_day(Количество_дней) - 20),2)

    else:
      return round((car_day(Количество_дней) - 50),2)
  
  
  total = hotel_cost(Количество_ночей) + plane_ride_cost(Город) + rental_car_cost(Количество_дней)

  print (f"Общая сумма путешествия составляет {total} у.е.")

In [ ]:
trip_cost()

Количество дней отпуска: 9
Место отдыха (Крым, Шри-Ланка, Каир или Сочи): Крым
Количество дней аренды автомобиля: 5


'Такого места нет'

Напишите функцию-генератор, которая будет выводить числа Фибоначчи.

In [ ]:
n = int(input())
if n == 0:
    print(0)
else:
    a, b = 0, 1
    for i in range(2, n + 1):
        a, b = b, a + b
    print(b)

In [ ]:
# Красиво 

def fib_to(n):
  fibs = [0, 1]
  for i in range(2, n+1):
    fibs.append(fibs[-1] + fibs[-2])
  return fibs

fib_to(20)

[0,
 1,
 1,
 2,
 3,
 5,
 8,
 13,
 21,
 34,
 55,
 89,
 144,
 233,
 377,
 610,
 987,
 1597,
 2584,
 4181,
 6765]

In [ ]:
fib_range=[1, 1]
maximum = int(input("Enter the range for Fibbonachi's digits: "))
print("#1 - ", fib_range[0])
print("#2 - ", fib_range[1])
for iteration in range(2,maximum):
    fib_range.append(fib_range[iteration-2]+fib_range[iteration-1])
    print("#", iteration + 1, " - ", fib_range[iteration])

Enter the range for Fibbonachi's digits: 10
#1 -  1
#2 -  1
# 3  -  2
# 4  -  3
# 5  -  5
# 6  -  8
# 7  -  13
# 8  -  21
# 9  -  34
# 10  -  55


In [ ]:
def fun_gen_fib(n):
    num1 = 1
    num2 = 1

    for i in range(n):
        yield num1

        var = num2
        num2 = num2 + num1
        num1 = var 


print(list(fun_gen_fib(10)))

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]


In [ ]:
M = {0: 0, 1: 1}

def fib(n):
    if n in M:
        return M[n]
    M[n] = fib(n - 1) + fib(n - 2)
    return M[n]

fib(10)

55

In [ ]:
a = 1
b =  5 

a, b = b, a + b 

a, b 

(5, 6)

In [ ]:
a = 1
b = 5

t = b 
b = a + b 
a = t 

a,b


(5, 6)

In [ ]:
matrix = []
for _ in range(5):
    matrix.append([0, 0, 0, 0, 0])

matrix

[[0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0]]

In [ ]:
table_cards = ["A_S", "J_H", "7_D", "8_D", "10_D"]
hand_cards = ["J_D", "3_D"]
s = 0 
for i in table_cards:
  #if 1 ==  hand_cards[i].count('D'):
    s = i
  #print (s)

hand_cards[0].count('D')

1

In [ ]:
table_cards = ["A_S", "J_H", "7_D", "8_D", "10_D"]
hand_cards = ["J_D", "3_D"]

t_D =  table_cards[0].count('D') + table_cards[1].count('D') + table_cards[2].count('D') + table_cards[3].count('D') + table_cards[4].count('D')
h_D =  hand_cards[0].count('D') + hand_cards[1].count('D')

t_C =  table_cards[0].count('C') + table_cards[1].count('C') + table_cards[2].count('C') + table_cards[3].count('C') + table_cards[4].count('С')
h_C =  hand_cards[0].count('C') + hand_cards[1].count('C')

if t_D + h_D >= 5:
  print ("Flush!")

elif t_C + h_C >= 5:
  print ("Flush!")

elif t_H + h_H >= 5:
  print ("Flush!")

elif t_S + h_S >= 5:
  print ("Flush!")

else:
  print ("No Flush!")


Flush!


In [ ]:
table_cards = ["A_S", "J_D", "7_S", "8_D", "10_D"]
hand_cards = ["J_D", "3_D"]

t_D = sum(map(lambda x : 1 if 'D' in x else 0, table_cards)) 
t_C = sum(map(lambda x : 1 if 'C' in x else 0, table_cards)) 
t_H = sum(map(lambda x : 1 if 'H' in x else 0, table_cards))
t_S = sum(map(lambda x : 1 if 'S' in x else 0, table_cards)) 

h_D = sum(map(lambda x : 1 if 'D' in x else 0, hand_cards)) 
h_C = sum(map(lambda x : 1 if 'C' in x else 0, hand_cards)) 
h_H = sum(map(lambda x : 1 if 'H' in x else 0, hand_cards))
h_S = sum(map(lambda x : 1 if 'S' in x else 0, hand_cards)) 

#print (t_D, t_C, t_H, t_S)
#print (h_D, h_C, h_H, h_S)

if t_D + h_D >= 5:
  print ("Flush!")

elif t_C + h_C >= 5:
  print ("Flush!")

elif t_H + h_H >= 5:
  print ("Flush!")

elif t_S + h_S >= 5:
  print ("Flush!")

else:
  print ("No Flush!")

Flush!


In [ ]:
# С помощью цикла for 
table_cards = ["A_S", "J_H", "7_D", "8_D", "10_D"]
hand_cards = ["J_D", "3_D"]

table_suits = [i[-1]for i in table_cards]
hand_suits = [i[-1]for i in hand_cards]

suits_in_game = table_suits + hand_suits

print (table_suits)
print (hand_suits)
print (suits_in_game)

flush = False

for suit in 'SHCD':
  if suits_in_game.count(suit) >= 5:
    flush = True

if flush:
  print ("Flush!")
else:
  print ("No Flush!")



['S', 'H', 'D', 'D', 'D']
['D', 'D']
['S', 'H', 'D', 'D', 'D', 'D', 'D']
Flush!


['S', 'H', 'D', 'D', 'D', 'D', 'D']

In [ ]:
# С помощью list comprehension

table_cards = ["A_S", "J_H", "7_D", "8_D", "10_D"]
hand_cards = ["J_D", "3_D"]

table_suits = [i[-1]for i in table_cards]
hand_suits = [i[-1]for i in hand_cards]

suits_in_game = table_suits + hand_suits

flush = any([suits_in_game.count(suit) >= 5 for suit in 'CHSD'])

if flush:
  print ("Flush!")
else:
  print ("No Flush!")



['S', 'H', 'D', 'D', 'D']
['D', 'D']
['S', 'H', 'D', 'D', 'D', 'D', 'D']
Flush!


In [ ]:
# палиндром 
number = int(input("Введите число:"))

reverse_number = 0
copy_tmp = number 

while copy_tmp > 0:
  reverse_number = (reverse_number * 10) + copy_tmp % 10
  copy_tmp  = copy_tmp // 10

if reverse_number == number:
  print ("Palindrome")
else:
  print ("No Palindrome")

Введите число:1221
Palindrome


In [ ]:
# Угадай число 

import numpy as np
n = np.random.randint(1, 51)

for i in range(6):
  num = int(input("Введите число от 1 до 50: "))
  if num > 50 or num < 1:
    print ("Вы нарушили правило игры и ввели не верное число.")
    break 
  if num == n:
    print ("Число угадано!!!!")
    break
  elif n < num:
    print ("Загаданное число меньше")
  elif n > num:
    print ("Загаданное число больше")

if n != num:
  print ("Больше попыток нет, увы Вы проиграли") 

Введите число от 1 до 50: 25
Загаданное число больше
Введите число от 1 до 50: 37
Загаданное число меньше
Введите число от 1 до 50: 31
Загаданное число меньше
Введите число от 1 до 50: 28
Загаданное число больше
Введите число от 1 до 50: 30
Загаданное число меньше
Введите число от 1 до 50: 29
Число угадано!!!!


In [ ]:
q = 1
while q <= 10:
    w = 1
    while w <= 10:
        print(q * w, end=" ")
        w += 1
    q += 1
    print("+")

1 2 3 4 5 6 7 8 9 10 +
2 4 6 8 10 12 14 16 18 20 +
3 6 9 12 15 18 21 24 27 30 +
4 8 12 16 20 24 28 32 36 40 +
5 10 15 20 25 30 35 40 45 50 +
6 12 18 24 30 36 42 48 54 60 +
7 14 21 28 35 42 49 56 63 70 +
8 16 24 32 40 48 56 64 72 80 +
9 18 27 36 45 54 63 72 81 90 +
10 20 30 40 50 60 70 80 90 100 +


In [ ]:
strange_phonebook = [
    ["Alex", "Andrew", "Aya", "Azazel"],
    ["Barry", "Bill", "Brave", "Byanka"],
    ["Casey", "Chad", "Claire", "Cuddy"],
    ["Dana", "Ditrich", "Dmitry", "Donovan"]
]
# это список списков, где каждый подсписок состоит из строк
# следовательно можно (зачем-то) применить тройной for
# для посимвольного чтения всех имён
# и вывода их в одну строку
for letter in strange_phonebook:
    for name in letter:
        for character in name:
            print(character, end=' ')

A l e x A n d r e w A y a A z a z e l B a r r y B i l l B r a v e B y a n k a C a s e y C h a d C l a i r e C u d d y D a n a D i t r i c h D m i t r y D o n o v a n 

In [ ]:
my_list = ['яблоко', 'банан', 'вишня', 'персик']
for c, value in enumerate(my_list):
    print(c, value)

0 яблоко
1 банан
2 вишня
3 персик


In [ ]:
my_list = ['яблоко', 'банан', 'вишня', 'персик']
for value in enumerate(my_list, 1):
    print(value)

(1, 'яблоко')
(2, 'банан')
(3, 'вишня')
(4, 'персик')


In [ ]:
matrix = [[71, 1, 7,43, 65] ,[50, 74, 93, 24, 42] ,[69, 92, 46, 36, 54], [45, 89, 81, 70, 18], [39, 11, 84, 40, 30]]

max_num = 0
min_num = 0

for i in matrix:
  for j in i:
    if j > max_num:
      max_num = j

min_num = max_num

for i in matrix:      
  for t in i:
    if t < min_num:
      min_num = t
  

print (max_num)
print (min_num)

93
1


In [ ]:
import numpy as np
arr1 = np.array([np.random.randint(1,100,(3,4))])
arr2 = np.array([np.random.randint(1,100,(4,3))])

print (arr1)
print (arr2)

arr2.dot(arr1)

[[[21 46 34 68]
  [11 57 75 21]
  [74 92 47 94]]]
[[[97 66 92]
  [81 23 94]
  [89 51 84]
  [22 20 37]]]


array([[[[ 9571, 16688, 12572, 16630]],

        [[ 8910, 13685,  8897, 14827]],

        [[ 8646, 14729, 10799, 15019]],

        [[ 3420,  5556,  3987,  5394]]]])

In [ ]:
import numpy as np

In [ ]:
# Для примера данной задачи создадим три матрицы. Размерами 4х3, 5х4 и 3х5 (размеры взяты произвольно)
m1 = np.random.randint(1,10,(4,3))
m2 = np.random.randint(1,10,(3,5))
m3 = np.random.randint(1,10,(5,4))


# Выведем на экран эти матрицы
print ("4x3:\n",m1)
print ("\n3x5:\n",m2)
print ("\n6x5:\n",m3)

4x3:
 [[1 7 6]
 [4 3 7]
 [2 8 9]
 [6 9 5]]

3x5:
 [[9 8 8 3 3]
 [8 1 7 8 3]
 [3 2 1 1 4]]

6x5:
 [[4 1 4 3]
 [9 9 7 9]
 [2 6 3 1]
 [9 7 1 3]
 [6 9 6 1]]


In [ ]:
def prod_three_matrix(matrix1, matrix2, matrix3):

  shape1 = matrix1.shape
  shape2 = matrix2.shape
  shape3 = matrix3.shape

  # Ветвь - 1  (Умножение первой на вторую матриц. И далее возможность умножить на третью. Или третью на результат (1 и 2) )

  # Если можно умножить первую матрицу на вторую 
  if (shape1[1] == shape2[0]):                                  # Смотрим возможность умножения матриц (сраниваем размеры столбцов матрицы 1 и строк матрицы 2)
    intermediate_matrix = np.zeros((shape1[0], shape2[1]))      # Создаем нулевую матрицу с размерами равную кол-ву строк матрицы 1 и столбцов матрицы 2
    for i in range(shape1[0]):
      for j in range(shape2[1]):
        hoarder = 0
        for n in range(shape1[1]):
          hoarder += matrix1[i,n] * matrix2[n,j] 
        intermediate_matrix[i,j] = hoarder
    
    # Если можно умножить результат (1 и 2) на третью матрицу
    if (shape2[1] == shape3[0]):
      total_matrix = np.zeros((shape1[0], shape3[1]))
      for i in range(shape1[0]):
        for j in range(shape3[1]):
          hoarder = 0
          for n in range(shape2[1]):
            hoarder += intermediate_matrix[i,n] * matrix3[n,j] 
          total_matrix[i,j] = hoarder
      return total_matrix
    
    # Если третья матрица такая, что невозмонжо умножить результат (1 и 2) на третью матрицу, но возможно третью умножить на результат (1 и 2). 
    elif (shape3[1] == shape1[0]):
      total_matrix = np.zeros((shape3[0], shape2[1]))
      for i in range(shape3[0]):
        for j in range(shape2[1]):
          hoarder = 0
          for n in range(shape3[1]):
            hoarder += matrix3[i,n] * intermediate_matrix[n,j]
          total_matrix[i,j] = hoarder
      return total_matrix
    
    else:
      return print("Третья матрица не подходящего размера. Умножение невозможно. Результат матричного умножения 1 и 2 матриц:\n", intermediate_matrix)

  
  # Ветвь - 2
  #elif (shape1[1] == shape3[0])

  # Если ни одно из условий не выполнилось и матрицы не подходящего размера, тогда вернуть пустой массив.
  else:
    return np.array([])
  

m = prod_three_matrix(m1, m2, m3)
m

array([[1574., 1591., 1063.,  798.],
       [1566., 1624., 1184.,  922.],
       [2083., 2120., 1448., 1089.],
       [2644., 2690., 1866., 1492.]])

In [ ]:
m1m2 = m1 @ m2

m1m2 @ m3

#m3 @ m1m2

array([[1574, 1591, 1063,  798],
       [1566, 1624, 1184,  922],
       [2083, 2120, 1448, 1089],
       [2644, 2690, 1866, 1492]])

In [ ]:
import numpy as np 
x = np.arange(-10,10)
len_x = x.shape[0]
len_x

20

In [ ]:
import numpy as np
i = 1

while i :
  game =  input("Введите букву: R - камень, S - ножницы, P - бумага: ")
  n = np.random.randint(1, 4)
  if n == 1 and game == 'R':
    print ("Ничья попробуйте снова")
  elif n == 1 and game == 'S':
    print ("Вы проиграли. Не расстраивайтесь, попробуйте еще раз")
  elif n == 1 and game == 'P':
    print ("Ура!!! Вы победили!") 
  
  elif n == 2 and game == 'R':
    print ("Ура!!! Вы победили!")
  elif n == 2 and game == 'S':
    print ("Ничья попробуйте снова")
  elif n == 2 and game == 'P':
    print ("Вы проиграли. Не расстраивайтесь, попробуйте еще раз") 

  elif n == 3 and game == 'R':
    print ("Вы проиграли. Не расстраивайтесь, попробуйте еще раз")
  elif n == 3 and game == 'S':
    print ("Ура!!! Вы победили!") 
  elif n == 3 and game == 'P':
    print ("Ничья попробуйте снова") 



In [ ]:
D = {x : x**2 for x in range(1,11)}
print(D)
print(10 in D)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}
True


# Задача - Кто выстрелил быстрее

In [ ]:
def whos_first(p1, p2):
    s1 = 0
    s2 = 0
    
    for i in p1:
        if i == 'B':
            break
        s1 += 1
    
    for i in p2:
        if i == 'B':
            break
        s2 += 1
    
    if s1 < s2:
        return "p1"
    elif s2 < s1:
        return "p2"
    else:
        return "tie"

In [ ]:
p1 = "     Bang!    "
p2 = "   Bang!  "

whos_first(p1, p2)

'tie'

# Задача - Ханойские башни

In [ ]:
def solve_hanoi_tower(discs):
    if discs == 0:
        return 0
    elif discs == 1:
        return 1
    elif discs == 2:
        return 2
    elif discs == 3:
        return 7
    s = 7
    for i in range (4, discs+1):
        s = s * 2 + 1
    
    return s


solve_hanoi_tower(4)

15

# Задача - Без дуплетов

In [ ]:
def calc_dice_scores(lst):
    s = 0

    for i in lst:
        s1 = 0 
        for j in i:
            if s1 == j:
                return 0
            s1+= j
  
        s += s1
    return s

lst = [(1,4), (3,4), (2,6)]

calc_dice_scores(lst)

20

In [ ]:
def calc_dice_scores(lst):
  return sum([a + b for a,b in lst]) if not any([a==b for a, b in lst]) else 0 

lst = [(1,4), (6,6), (2,6)]
calc_dice_scores(lst)


0

# Задача - Мини Судоку

In [ ]:
def any_duplicates(square):
  lst = []
  for i in square:
    for j in i:
      if j in lst:
        return True
      lst.append(j) 
  return False

square = ([[1,2,3], [4,5,6], [7,8,9]])

any_duplicates(square)

False

# Задача - Палочки

In [ ]:
pal = int(input("Введите количество палочек: "))
y = 0

while pal>1:
  t = y
  g1 = int(input("Первый игрок берет:"))
  t = pal - g1 
  print (f"На столе остается: {t} палочек")
  if t == 1:
    print ("Победа 1 игрока")
    break
  pal = t

  g2 = int(input("Второй игрок берет: "))
  y = t - g2 
  print (f"На столе остается: {y} палочек")
  if y == 1:
    print ("Победа 2 игрока")
    break
  pal = y


Введите количество палочек: 10
Первый игрок берет:3
На столе остается: 7 палочек
Второй игрок берет: 2
На столе остается: 5 палочек
Первый игрок берет:1
На столе остается: 4 палочек
Второй игрок берет: 3
На столе остается: 1 палочек
Победа 2 игрока
