### Задача 1

Создайте целочисленный массив Numpy. Для этого выполните следующее:
1. Создайте список из целых значений (не меньше 5 штук).
2. Используя метод numpy.array(), переведите список в массив Numpy.

**Решение:**

In [ ]:
import numpy as np

# Способ 1

my_list = [23, 88, 126, 49, 287, 92, 7543, 592]
my_array = np.array(my_list)
print (my_array)   

# Способ 2

my_array2 = np.array ([2, 4 ,8, 16, 32, 64, 128, 256])
print (my_array2)   

# Способ 3

my_array3 = np.array([i for i in range(0,30, 3)])
print (my_array3)   

[  23   88  126   49  287   92 7543  592]
[  2   4   8  16  32  64 128 256]
[ 0  3  6  9 12 15 18 21 24 27]


###Задача 2

Используя индексы, выведите первый и третий элемент массива.


**Решение:**

In [ ]:
print ("Первый элемент массива:", my_array[0])
print ("Третий элемент массива:", my_array[2])

Первый элемент массива: 23
Третий элемент массива: 126


###Задача 3

Используя метод type(), проверьте тип созданного массива. 


**Решение:**

In [ ]:
print(type (my_array))
print(type (my_array2))
print(type (my_array3)) 

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


###Задача 4

Используя метод sum(), найдите сумму всех элементов массива. 


**Решение:**

In [ ]:
sum_my_array = my_array.sum()
sum_my_array2 = my_array2.sum()

print("Сумма массива my_array:", sum_my_array)
print("Сумма массива my_array2:", sum_my_array2)
print("Сумма массива my_array3:", my_array3.sum())


Сумма массива my_array: 8800
Сумма массива my_array2: 510
Сумма массива my_array3: 135


###Задача 5

Используя метод arange(), создайте новый массив из значений от 0 до 10.


**Решение:**

In [ ]:
my_array_arange = np.arange(11)
print (my_array_arange)

[ 0  1  2  3  4  5  6  7  8  9 10]
