### Задача 1

Создайте единичную матрицу размером 5*5.

**Должна получиться матрица вида**

**1** 0 0 0 0 

0 **1** 0 0 0 

0 0 **1** 0 0 

0 0 0 **1** 0 

0 0 0 0 **1** 

**Действовать можно двумя путями:**

1. Используя соответствующий метод Numpy. (О нем не говорилось в занятии. Стоит обратиться к документации Numpy).
2. Если первый вариант сложный, можно создать массив из нулей, используя метод, о котором говорилось в занятии. В цикле заменить все элементы по диагонали на единицы. 






**Решение:**

In [ ]:
import numpy as np                 #Подключение библиотеки numpy

my_array = np.eye(5)               #Создание единичной матрицы 5х5 с помощью метода eye
print (my_array)                   #Вывод созданной матрицы 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


###Задача 2

Создайте массив из случайных значений из стандартного нормального распределения размера 6 на 6. 

Разверните массив таким образом, чтобы его размер стал 36 на 1.
Найдите среднее значение элементов массива.

**Разрешается использовать только методы Numpy. (Циклы и условия запрещены)**.

**Решение:**

In [ ]:
normal_array = np.random.normal (1, 10, (6,6))                # Создание массиива из случайных значений из стандартного нормального распределения размера 6 на 6.
normal_array_new = normal_array.reshape (36,1)                # Изменяем размерность массива 
print ("Размерность массива:", normal_array_new.shape)        # Проверка размерности массива
mean = normal_array_new.mean()                                # Находим среднее значение массива с помощью метода mean и присваеваем переменной
print ("Среднее значение данного маасива:", mean)             # Выводим на экран значение переменной в короторой хранится среднее значение массива 

print ("Другим способом вывести:", normal_array_new.mean())   # Второй способ, без переменной, сразу на экран

Размерность массива: (36, 1)
Среднее значение данного маасива: 1.2678560035077953
Другим способом вывести: 1.2678560035077953


###Задача 3

Создайте массив из 20 любых случайных значений, используя метод Numpy.
При помощи срезов и операций с массивами найдите значения производных для созданного массива

**Решение:**

In [ ]:
my_array_3 = np.random.randint(0, 10, (20))                     # Создадим массив размером 20 из случайных чисел

print ("Созданный массив:", my_array_3)                         # Вывести массив на экран
print ("Размер массива:", my_array_3.size)                      # Размерность созданного массива


slice_array = my_array_3[1:]                                    # Создаем массив а со срезом (начиная со втрого элемента)
print ("\nМассив со срезом, начиная со второго элемента:",slice_array)    
print ("Размер массива:", slice_array.size)                        

der = slice_array - my_array_3[:-1]                               # Вычетаем из массива (со срезом) изначально созданный массив (кроме последнего элемента) 
print ("\nЗначения производных:",der)
print ("Размер массива:", der.size) 


#Второй способ

der_2 = np.diff(my_array_3)                                           # Вычисляем производную данного массива. Результат присваеваем переменной der_2 
print ("\nПроизводная массива вторым способом с помощью diff:", der_2)                 # Вывод на экран нового массива (размерность -1)
print ("Размер массива:", der_2.size)                                 # Размерность массива




Созданный массив: [1 4 8 6 0 7 3 6 8 8 1 8 6 3 0 5 6 4 7 1]
Размер массива: 20

Массив со срезом, начиная со второго элемента: [4 8 6 0 7 3 6 8 8 1 8 6 3 0 5 6 4 7 1]
Размер массива: 19

Значения производных: [ 3  4 -2 -6  7 -4  3  2  0 -7  7 -2 -3 -3  5  1 -2  3 -6]
Размер массива: 19

Производная массива вторым способом с помощью diff: [ 3  4 -2 -6  7 -4  3  2  0 -7  7 -2 -3 -3  5  1 -2  3 -6]
Размер массива: 19


###Задача 4

Дано выражение

Y = A * X * C

Создайте три случайных массива A, C, X. Размерности должны позволять выполнить матричное умножение согласно формуле. На выходе должен получиться массив Y с размерностью (5, 18). (Остальные размерности возьмите на свое усмотрение).

**Решение:**

In [ ]:
A = np.random.randint (0, 5, (5,3))              # Создаем массив размерностью 5 на 3 из случайных чисел
X = np.random.randint (0, 5, (3,2))              # Создаем массив размерностью 3 на 2 из случайных чисел
C = np.random.randint (0, 5, (2,18))             # Создаем массив размерностью 2 на 18 из случайных чисел

mult = A.dot(X)                                  # Выполняем матричное умножения массивов А на Х. Переменной mult присваеваем результат. 
Y = mult.dot(C)                                  # Выполняем матричное умножения массива mult и С. Переменной Y присваеваем результат. 

print (Y)                                        # Вывод на экран массив Y 
print (Y.shape)                                  # Проверка размерности массива Y

[[ 36  39  39  72  63  39  45  36  12  60  48   9  18  36  72  72  51  12]
 [ 30  73  73 114  93  73  51  30  10 104  40  21  42  84 114 114  83  10]
 [ 45  78  78 129 108  78  66  45  15 114  60  21  42  84 129 129  93  15]
 [ 27  45  45  75  63  45  39  27   9  66  36  12  24  48  75  75  54   9]
 [ 12  31  31  48  39  31  21  12   4  44  16   9  18  36  48  48  35   4]]
(5, 18)


###Задача 5

Загрузите какой-либо файл с данными (таблица Excel с Вашего компьютера, сохраненная в формате csv, или таблица из Интернета). Выведите следующее:

1. Всю информацию из файла в ячейку. 
2. Размерность данных. 
3. Среднее арифметическое от всех числовых значений (если есть).
4. Число столбов. 
5. Число строк.
6. Типы данных всех значений. 

**Решение:**

In [ ]:
my_data = np.loadtxt('My_array.csv', delimiter=',', skiprows=1)
print ("Информация из файла:\n")
print (my_data)
print ("\nРазмерность данных:", my_data.shape)
print ("\nСреднее арифметическое от всех числовых значений:", my_data.mean())
print ("\nЧисло столбов:", my_data.shape[1])
print ("\nЧисло строк:", my_data.shape[0])
print ("\nТип данных:", my_data.dtype)

print ("\nТип переменной my_data:", type(my_data))  #Посмотреть тип переменной my_data в задании не было, просто для примера




Информация из файла:

[[5041.   56.  657.   54.]
 [8536.  645.   57.   37.]
 [1979.   24.   19.   87.]
 [  16.   95.   47.   26.]
 [  78.   34.   90.   23.]
 [  50.   46.   78.   34.]
 [  94.   23.   56.   76.]
 [  21.   93.   54.   46.]
 [  12.   47.   38.   29.]]

Размерность данных: (9, 4)

Среднее арифметическое от всех числовых значений: 511.05555555555554

Число столбов: 4

Число строк: 9

Тип данных: float64

Тип переменной my_data: <class 'numpy.ndarray'>
