#Задача 1

* Создайте скаляр
* Создайте вектор размера 5
* Создайте матрицу размера 5х5

Выведите все три переменные на экран, если это возможно, выведите их форму и общее число элементов

**Решение**:

In [ ]:
# Импортируем библиотеку numpy
import numpy as np 

In [ ]:
# Создание скаляра
scalar = 5    

# Создание вектора
vector = np.array([4.3, 8, -17.5, 11, 0.7])   

# Создание матрицы 5х5
array = np.array([[1, 5, 7 ,3, 9], [32, -5, 2, 73, 1], [25, 72,-15, 3, -7], [8, -5, 25, 62, -25], [1, 63, 28, -6, 4]])

# Так же можно создать матрицу 5х5 с помощью метода random.
array_rnd = np.random.randint(0,100, (5,5))

In [ ]:
# Вывод всех трех переменных на экран
print ("Скаляр: ",sсalar)
print ("\nВектор: ",vector)
print ("\nМатрица: \n",array)
print ("\nМатрица c помощью метода random: \n",array_rnd)

Скаляр:  5

Вектор:  [  4.3   8.  -17.5  11.    0.7]

Матрица: 
 [[  1   5   7   3   9]
 [ 32  -5   2  73   1]
 [ 25  72 -15   3  -7]
 [  8  -5  25  62 -25]
 [  1  63  28  -6   4]]

Матрица c помощью метода random: 
 [[66 66 55 10 83]
 [27 34 27 34 23]
 [ 6 25 56 97 37]
 [89 90 73 84 71]
 [40 41 21 31 34]]


In [ ]:
# Вывод формы и размера
print ("Форма вектора: ", vector.shape) 
print ("Форма матрицы: ", array.shape)

print ("\nЧисло элементов вектора: ", vector.size)
print ("Число элементов матрицы: ", array.size)

Форма вектора:  (5,)
Форма матрицы:  (5, 5)

Число элементов вектора:  5
Число элементов матрицы:  25


#Задача 2

Возьмите переменные, которые вы получили в предыдущей задаче.

* Сложите скаляр с вектором
* Умножьте скаляр на вектор
* Поделите матрицу на скаляр
* Сложите матрицу со скаляром
* Сложите матрицу с вектором - такая операция не разбиралась на занятии. Посмотрите, получится ли это сделать

**Решение:**

In [ ]:
# 1
# Сложение скаляра с вектором
print ("Результат сложение скаляра с вектором:", scalar + vector)

Результат сложение скаляра с вектором: [  9.3  13.  -12.5  16.    5.7]


In [ ]:
# 2
# Умножение скаляра на вектором
print ("Результат умножение скаляра на вектор:", scalar * vector)


Результат умножение скаляра на вектор: [ 21.5  40.  -87.5  55.    3.5]


In [ ]:
# 3
# Деление матрицы на скаляр
print ("Результат деления матрицы на скаляр:\n", array / scalar)

Результат деления матрицы на скаляр:
 [[ 0.2  1.   1.4  0.6  1.8]
 [ 6.4 -1.   0.4 14.6  0.2]
 [ 5.  14.4 -3.   0.6 -1.4]
 [ 1.6 -1.   5.  12.4 -5. ]
 [ 0.2 12.6  5.6 -1.2  0.8]]


In [ ]:
# 4
# Сложение матрицы со скаляром
print ("Результат сложения матрицы со скаляром:\n", array + scalar)

Результат сложения матрицы со скаляром:
 [[  6  10  12   8  14]
 [ 37   0   7  78   6]
 [ 30  77 -10   8  -2]
 [ 13   0  30  67 -20]
 [  6  68  33  -1   9]]


In [ ]:
# 5
# Сложение матрицы с вектором
print ("Результат сложения матрицы с вектором:\n", array + vector)

print ("\nПолучилось сложение каждой строки матрицы с данным вектором")

Результат сложения матрицы с вектором:
 [[  5.3  13.  -10.5  14.    9.7]
 [ 36.3   3.  -15.5  84.    1.7]
 [ 29.3  80.  -32.5  14.   -6.3]
 [ 12.3   3.    7.5  73.  -24.3]
 [  5.3  71.   10.5   5.    4.7]]

Получилось сложение каждой строки матрицы с данным вектором


#Задача 3

Возьмите переменную с матрицей из предыдущих заданий.
С помощью соответствующих методов:

* Транспонируйте матрицу
* Найдите обратную матрицу
* Матрично умножьте саму на себя

**Решение:**

In [ ]:
# 1

# Выведем первоначальную матрицу
print ("Первоначальная матрица: \n",array)
print ("")

# Транспонируем матрицу
array_trans = array.transpose()
print ("Методом transpose:\n ", array_trans)

# Так же можно с помощью более простого написания
array_t = array.T
print ("\nМетодом .T:\n ", array_t)


# 2

# Найдем обратную матрицу с помощью специального метода np.linalg.inv()
array_inverse = np.linalg.inv(array)
print ("\nОбратная матрица:\n ", array_inverse)

# 3

# Матрично умножим матрицу саму на себя
# Сразу вывдем на экран

print ("\nМатричное умножение матрицы array самой на себя:\n\n С помощью метода .dot:\n",array.dot(array))

print("\nС помощью оператора @:\n", array @ array)

Первоначальная матрица: 
 [[  1   5   7   3   9]
 [ 32  -5   2  73   1]
 [ 25  72 -15   3  -7]
 [  8  -5  25  62 -25]
 [  1  63  28  -6   4]]

Методом transpose:
  [[  1  32  25   8   1]
 [  5  -5  72  -5  63]
 [  7   2 -15  25  28]
 [  3  73   3  62  -6]
 [  9   1  -7 -25   4]]

Методом .T:
  [[  1  32  25   8   1]
 [  5  -5  72  -5  63]
 [  7   2 -15  25  28]
 [  3  73   3  62  -6]
 [  9   1  -7 -25   4]]

Обратная матрица:
  [[-1.02270811  0.28410517 -0.21865508 -0.24208428  0.33439382]
 [ 0.26194357 -0.07141018  0.06474105  0.06055297 -0.07976761]
 [-0.49454812  0.13309111 -0.12287512 -0.10925742  0.18157012]
 [ 0.4756184  -0.11861269  0.10297047  0.11270286 -0.15589706]
 [ 0.30533021 -0.05587266  0.04957381  0.04066809 -0.08209505]]

Матричное умножение матрицы array самой на себя:

 С помощью метода .dot:
 [[  369  1036   239   521   -74]
 [  507    27  2037  4257 -1552]
 [ 1971 -1771   423  5514   299]
 [  944   -20   521  3728 -1758]
 [ 2673  1988  -325  4290    42]]

С помощью

# Задача 4

Создайте любым удобным способом "ось Х"- 1000 целых значений от 0 до 1000 не включительно. Выведите получившийся массив на экран. Напишите ответ, что вы получили: скаляр, вектор или матрицу

In [ ]:
# С помощью библиотеки numpy и метода random cозданим массив
axis_x = np.array([np.random.randint(0,1000,1000)])

# Создадим горизонтальный вектор
axis_x = axis_x.reshape (1000)

print ("Получился горизонтальный вектор размером:",axis_x.shape)

# выведем получившийся массив
print ("\n",axis_x)



Получился горизонтальный вектор размером: (1000,)

 [913 571 850 791 684 425  36 746 687 714 318 363 837 220 440 992 607 807
 100 926  33 836 714 472 505 492 254 544 704 986 212 962 327 696 825  46
 513 910 961 370 932 143 912 640 993 862 546  46 496 826 277 527 590 812
 597 979 105 904 725 478 102 399 389 410 148 526  29 614 291 645 736 159
 223 162 187 896 822 929 608 872 359 827 208 184 635 974 296 791 292 917
 766 165 340  50 135 231  47 617 726 613 721  45 287 622 289 972 270 164
 201 125 224 600 800 955  44 729 495 142 504 945 926 515 283 886 406 954
 840 458 315 857 926 816 111  21 686 918 874 131 903 233  42 319 221 447
 903 967 136 949 518 694 789 863 571 684 522  68 206  11 786 802 612 791
 672 863 426 585 322 349   2 278 708 150 272  48 574 535 532 301 292 269
 605 261 592 261 970 560 280 883 600 288 414 104 126 363  33 896 190 771
 469 887 541  78 650 814 466 248 662 694 429 199 596 504 470 773 411 539
 887 974 671 945 594 319 610 342 731 354 374 460 607 489 518 932 319 531